# Generated by Django 4.1.1 on 2022-10-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='number_bedrooms',
            new_name='num_bedrooms',
        ),
    ]
