# Generated by Django 4.1.1 on 2022-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_number_bedrooms_house_num_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='images',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
