# Generated by Django 4.1.1 on 2022-10-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='images',
            new_name='image',
        ),
    ]
